import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import util from 'util';

const execPromise = util.promisify(exec);

/** @type {import('./$types').RequestHandler} */
export async function POST({ request }) {
  try {
    const product = await request.json();
    const jsonPath = path.resolve('src/lib/products.json');
    
    // Execute teammate's python script to generate the tag label image
    try {
      await execPromise(`python qr_generator.py "${product.id}"`);
      
      const labelPath = path.resolve(`${product.id}_label.png`);
      if (fs.existsSync(labelPath)) {
        const buffer = fs.readFileSync(labelPath);
        // Save the python-generated PNG image base64 into the product's image field
        product.image = `data:image/png;base64,${buffer.toString('base64')}`;
        
        // Clean up the temporary label image file
        fs.unlinkSync(labelPath);
      }
      
      // Clean up the temporary barcode file generated by python script
      const tempBarcode = path.resolve('temp_barcode.png');
      if (fs.existsSync(tempBarcode)) {
        fs.unlinkSync(tempBarcode);
      }
    } catch (pyError) {
      console.error('Failed to run python label generator script:', pyError);
      // Keep going with the default passed image if python fails
    }
    
    let products = [];
    if (fs.existsSync(jsonPath)) {
      const fileContent = fs.readFileSync(jsonPath, 'utf8');
      products = JSON.parse(fileContent);
    }
    
    // Append the new product
    products.push(product);
    
    // Write back to products.json on disk
    fs.writeFileSync(jsonPath, JSON.stringify(products, null, 2), 'utf8');
    
    return new Response(JSON.stringify({ success: true, product }), {
      headers: { 'Content-Type': 'application/json' }
    });
  } catch (error) {
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
